In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Load the dataset
df = pd.read_csv('SkillCraft1_Dataset.csv')

In [2]:
df.head(5)

,GameID,LeagueIndex,Age,HoursPerWeek,TotalHours,APM,SelectByHotkeys,AssignToHotkeys,UniqueHotkeys,MinimapAttacks,MinimapRightClicks,NumberOfPACs,GapBetweenPACs,ActionLatency,ActionsInPAC,TotalMapExplored,WorkersMade,UniqueUnitsMade,ComplexUnitsMade,ComplexAbilitiesUsed
0,52,5,27,10,3000,143.7180,0.003515,0.000220,7,0.000110,0.000392,0.004849,32.6677,40.8673,4.7508,28,0.001397,6,0.0,0.000000
1,55,5,23,10,5000,129.2322,0.003304,0.000259,4,0.000294,0.000432,0.004307,32.9194,42.3454,4.8434,22,0.001193,5,0.0,0.000208
2,56,4,30,10,200,69.9612,0.001101,0.000336,4,0.000294,0.000461,0.002926,44.6475,75.3548,4.0430,22,0.000745,6,0.0,0.000189
3,57,3,19,20,400,107.6016,0.001034,0.000213,1,0.000053,0.000543,0.003783,29.2203,53.7352,4.9155,19,0.000426,7,0.0,0.000384
4,58,3,32,10,500,122.8908,0.001136,0.000327,2,0.000000,0.001329,0.002368,22.6885,62.0813,9.3740,15,0.001174,4,0.0,0.000019

In [5]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load the dataset
df = pd.read_csv('SkillCraft1_Dataset.csv')

# Drop irrelevant columns (e.g., GameID, LeagueIndex)
df = df.drop(['GameID', 'LeagueIndex'], axis=1)

# Convert non-numeric values to NaN
df = df.apply(pd.to_numeric, errors='coerce')

# Drop rows with missing values
df = df.dropna()

# Separate the features from the target variable
X = df.drop('Age', axis=1)
y = df['Age']

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [17]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Load the dataset
df = pd.read_csv('SkillCraft1_Dataset.csv')

# Drop irrelevant columns (e.g., GameID, LeagueIndex)
df = df.drop(['GameID', 'LeagueIndex'], axis=1)

# Convert non-numeric values to NaN
df = df.apply(pd.to_numeric, errors='coerce')

# Drop rows with missing values
df = df.dropna()

# Separate the features from the target variable
X = df.drop('Age', axis=1)
y = df['Age']

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [18]:
# Apply PCA with n_component = 2
n = 2
pca = PCA(n_components=n)
X_pca = pca.fit_transform(X_scaled)

# Create a new data frame with the principal components
new_df = pd.DataFrame(data=X_pca, columns=[f"PC{i+1}" for i in range(n)])

# Display the new data frame
new_df.head(5)

        PC1       PC2
0 -1.422004  0.080119
1 -0.783346  0.525659
2  1.248162 -0.415555
3  0.400178 -0.181782
4  0.411395  2.882330

In [19]:
# Apply PCA with n_component = 5
n = 5
pca = PCA(n_components=n)
X_pca = pca.fit_transform(X_scaled)

# Create a new data frame with the principal components
new_df = pd.DataFrame(data=X_pca, columns=[f"PC{i+1}" for i in range(n)])

# Display the new data frame
new_df.head(5)

        PC1       PC2       PC3       PC4       PC5
0 -1.422002  0.080295 -1.247771 -0.935373 -1.037011
1 -0.783357  0.525733 -0.391171 -0.780631 -0.594334
2  1.248091 -0.420387 -0.101430 -1.110413  0.657052
3  0.400313 -0.172771  0.125170  0.066450 -0.673652
4  0.411258  2.875729  2.785235 -1.031815 -0.952650

In [20]:
# Apply PCA with n_component = 17
n = 17
pca = PCA(n_components=n)
X_pca = pca.fit_transform(X_scaled)

# Create a new data frame with the principal components
new_df = pd.DataFrame(data=X_pca, columns=[f"PC{i+1}" for i in range(n)])

# Display the new data frame
new_df.head(5)

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17
0,-1.422002,0.080305,-1.247747,-0.935301,-1.037003,0.560407,-0.131604,-0.205153,0.145576,0.375207,-0.141290,-1.335664,0.509562,-0.067454,0.263064,0.092747,0.027729
1,-0.783357,0.525711,-0.391224,-0.780791,-0.594351,0.381413,0.287406,1.114760,0.769603,-0.281557,0.550961,-0.993696,0.403350,0.346763,0.319578,-0.165272,0.026378
2,1.248091,-0.420405,-0.101471,-1.110538,0.657038,-0.199404,-0.087267,0.923053,0.468112,-0.040880,0.618742,-0.079052,0.095934,0.380607,-0.325487,-0.152278,-0.038255
3,0.400313,-0.172768,0.125176,0.066466,-0.673650,0.063751,1.472228,1.222692,-1.098495,-0.687909,0.354327,0.016377,-0.307648,0.840471,0.215790,0.048990,-0.098258
4,0.411258,2.875718,2.785210,-1.031894,-0.952658,0.572155,0.049212,0.107209,-1.696496,0.172986,0.534015,0.411941,0.475977,-0.221409,0.021733,-0.093678,0.135459